server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: transaction-manager

info:
  swagger: http://${spring.cloud.client.ip-address:localhost}:${server.port:8080}${server.servlet.context-path:/}swagger-ui.html
